/*
 * This file was automatically generated by EvoSuite
 * Mon May 23 13:35:35 GMT 2022
 */

package simplejavacalculatorESTest;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import simplejavacalculator.BufferedImageCustom;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BufferedImageCustom_ESTest extends BufferedImageCustom_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BufferedImageCustom bufferedImageCustom0 = new BufferedImageCustom();
      // Undeclared exception!
      try { 
        bufferedImageCustom0.imageReturn();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // input == null!
         //
         verifyException("javax.imageio.ImageIO", e);
      }
  }
}
